default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 123
  host: localhost

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production
  username: production_user
  password: <%= ENV['DATABASE_PASSWORD'] %>